
server:
  port: 8080
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations:
   - classpath: mapper/*.xml          # mbg生成的mapper文件
   - classpath: com/**/mapper/*.xml   # 自定义的mapper文件
logging:
  config: classpath:logback-spring.xml
  level:        # 打印sql语句
    dao: debug
    org:
      mybatis: debug

