
server:
  port: 8080
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liao.hw.mbg.entity
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug

